try {
    something(45);
} catch(error) {
    println(error);
}

try {
    something(45);
} finally {
    println("done");
}

try {
    something(45);
} catch(error) {
    println(error);
} finally {
    println("done");
}